export interface LancamentoDp {
    cpf: string,
    mes: string,
    ano: number,
    base: number,
    gratificacoes: number,
    ferias: number,
    outros: number,
    ajudaCusto: number,
    auxilioCombustivel: number,
    auxilioMoradia: number,
    horaExtra100: number,
    horaExtra50: number,
    premioPermanencia: number,
    premioTempoServico: number,
    reflexoHoraExtra: number,
    salarioFamilia: number,
    adicionalNoturno: number,
    diferencaSalario: number,
    gratificacaoFuncao: number,
    dsrGratificacao: number,
    reembolso: number,
    observacao: string,
    aprovadoRener: boolean
}
