CREATE TABLE lancamento_dp (
    id INT PRIMARY KEY IDENTITY(1,1),
    cpf VARCHAR(14) NOT NULL,
    mes VARCHAR(255),
    ano INT,
    base FLOAT DEFAULT 0,
    gratificacoes FLOAT DEFAULT 0,
    ferias FLOAT DEFAULT 0,
    outros FLOAT DEFAULT 0,
    ajuda_custo FLOAT DEFAULT 0,
    auxilio_combustivel FLOAT DEFAULT 0,
    auxilio_moradia FLOAT DEFAULT 0,
    hora_extra100 FLOAT DEFAULT 0,
    hora_extra50 FLOAT DEFAULT 0,
    premio_permanencia FLOAT DEFAULT 0,
    premio_tempo_servico FLOAT DEFAULT 0,
    reflexo_hora_extra FLOAT DEFAULT 0,
    salario_familia FLOAT DEFAULT 0,
    adicional_noturno FLOAT DEFAULT 0,
    diferenca_salario FLOAT DEFAULT 0,
    gratificacao_funcao FLOAT DEFAULT 0,
    dsr_gratificacao FLOAT DEFAULT 0,
    reembolso FLOAT DEFAULT 0,
    observacao VARCHAR(255),
    aprovado_rener BIT NULL
);
